language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6-dev"
  - "nightly"

before_install:
  - pip install codecov

install: "pip install -r requirements-dev.txt"

script: 
  - coverage run setup.py test

after_success:
  - codecov
