language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"

before_install:
  - pip install codecov

install: "pip install -r requirements.txt"

script: python setup.py test

after_success:
  - codecov
